services:
  mysql:
    image: mysql:8.0
    container_name: Eriks-trullo-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trullo
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
